export const EXPENSE_CATEGORY_OPTIONS = [
  { value: "役員報酬", label: "役員報酬" },
  { value: "給料手当", label: "給料手当" },
  { value: "雑給", label: "雑給" },
  { value: "法定福利費", label: "法定福利費" },
  { value: "福利厚生費", label: "福利厚生費" },
  { value: "外注費", label: "外注費" },
  { value: "旅費交通費", label: "旅費交通費" },
  { value: "車両費", label: "車両費" },
  { value: "通信費", label: "通信費" },
  { value: "交際費", label: "交際費" },
  { value: "諸会費", label: "諸会費" },
  { value: "会議費", label: "会議費" },
  { value: "地代家賃", label: "地代家賃" },
  { value: "リース料", label: "リース料" },
  { value: "保険料", label: "保険料" },
  { value: "修繕費", label: "修繕費" },
  { value: "水道光熱費", label: "水道光熱費" },
  { value: "消耗品費", label: "消耗品費" },
  { value: "租税公課", label: "租税公課" },
  { value: "広告宣伝費", label: "広告宣伝費" },
  { value: "支払手数料", label: "支払手数料" },
  { value: "荷造運賃", label: "荷造運賃" },
  { value: "支払利息", label: "支払利息" },
  { value: "支払報酬料", label: "支払報酬料" },
  { value: "雑費", label: "雑費" },
  { value: "短期借入金", label: "短期借入金" },
  { value: "長期借入金", label: "長期借入金" },
  { value: "その他", label: "その他" },
] as const;

export const DEFAULT_EXPENSE_CATEGORY = "その他";
